# Generated by Django 4.2.21 on 2025-05-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manutencao', models.CharField(choices=[('1', 'Computador'), ('2', 'Impressora'), ('3', 'Computador e Impresssora'), ('4', 'Outro')], max_length=30, verbose_name='Manutenção')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('data_up', models.DateTimeField(auto_now=True)),
                ('status_chamado', models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'FINALIZADO'), ('3', 'CANCELADO')], max_length=30, verbose_name='Chamado')),
            ],
        ),
    ]
