# Generated by Django 4.2.21 on 2025-06-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_chamada_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamada',
            name='status_chamado',
            field=models.CharField(choices=[('1', 'AGUARDANDO'), ('2', 'FINALIZADO'), ('3', 'CANCELADO')], default='1', max_length=30, verbose_name='Chamado'),
        ),
    ]
