# Generated by Django 4.2.21 on 2025-06-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_tecnico',
            field=models.BooleanField(default=False),
        ),
    ]
